ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ com.controlfinanciero.ApplicationKt.module ]
    }
}

database {
    url = "jdbc:postgresql://localhost:5432/control_financiero"
    url = ${?DATABASE_URL}
    driver = "org.postgresql.Driver"
    user = "postgres"
    user = ${?DATABASE_USER}
    password = "postgres"
    password = ${?DATABASE_PASSWORD}
}

mercadopago {
    accessToken = ${?MERCADOPAGO_ACCESS_TOKEN}
    baseUrl = "https://api.mercadopago.com"
}
